/** 同步 / 加载相关时序常量（毫秒） */
export const SYNC_TICK_MS = 1000;
export const SYNC_BATCH_POLL_MS = 5000;
export const SYNC_RESET_DELAY_MS = 800;
export const SYNC_MODAL_AUTO_CLOSE_MS = 1200;
export const DETAIL_NOT_FOUND_MS = 5000;
export const FAV_SEARCH_DEBOUNCE_MS = 300;
export const LOG_STICK_BOTTOM_PX = 50;
export const BACK_TOP_SHOW_Y = 480;
export const HISTORY_MAX = 20;
export const SIMILAR_LIMIT = 4;
export const PAGE_SIZE = 60;
